version: '3.8'
services:
  api:
    build:
      context: ./services/Encicla
      dockerfile: Dockerfile
    ports:
      - "5032:8080"  # Local:5032 -> container:8080 (mapeo de launchSettings)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Para CORS allow all en local
      - GeoData__MunicipalitiesPath=Encicla.API/StaticData/geo/municipalities.json
      - GeoData__NeighborhoodsByMunicipalityPath=Encicla.API/StaticData/geo/neighborhoods_by_municipality.json
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SenderName=Encicla App - Web form
      - EmailSettings__SenderEmail=tu-correo@gmail.com
      - EmailSettings__Username=tu-correo@gmail.com
      - EmailSettings__Password=tu-clave # Nota: Usar secrets en prod

  web-form:
    build:
      context: .
      dockerfile: apps/web-form/Dockerfile
    ports:
      - "3001:3000"  # Evita conflicto con otros
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5032/api
      - NEXT_PUBLIC_SECONDS_READ_PDF=5
      - NEXT_PUBLIC_FACE_WASM_URL=https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm
      - NEXT_PUBLIC_FACE_MODEL_URL=https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite
      - NEXT_PUBLIC_FACE_DELEGATE=CPU
    depends_on:
      - api

  # web-admin:
  #   build:
  #     context: .
  #     dockerfile: apps/web-admin/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_BASE_URL=http://api:8080/api
  #   depends_on:
  #     - api